config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :categories, only:[:index, :new, :create] do
    resources :transactions, only:[:index, :new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "splashes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions, through: :transaction

  validates :name, :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true
  has_many :categories

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(_resources)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to categories_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = Transaction.where(category_id: params[:category_id]).order('created_at DESC')
    @id = params[:category_id]
  end

  def new
    @id = params[:category_id]
  end

  def create
    transaction = Transaction.new(transaction_params)
    transaction.user_id = current_user.id
    redirect_to category_transactions_path(params[:transaction][:category_id])
    if transaction.save
      flash[:notice] = 'transaction created successfully'
    else
      flash[:alert] = 'Error occurred while creating the transaction'
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/views/categories/index.html.erb
<% @page_name = 'Categories' %>
<p style="color: green"><%= notice %></p>

<div class='categories'>  
  <% if @categories.empty? %>
      <p>no categories</p>      
    <% end %>
  <% @categories.each do |category| %>
    
    <div class='card'> 
      <div class='category-details'>
        <img src="<%= category.icon %>" alt='category-icon' />
        <%=link_to category.name, category_transactions_path(category.id), class:'name' %>
      </div>       
      
      <p>$<%= Transaction.where(category_id: category.id).sum(:amount) %> </p>
     
    </div>
    
  <% end %>
</div>

<%= link_to "New category", new_category_path, class: 'btn' %>

app/views/categories/new.html.erb
<% @page_name = 'New Categories' %>
<div class='category-form'>
  <%= form_with model: @category do |f| %> 
    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name, autocomplete: 'name', autofocus: true %>
      <% @category.errors.full_messages_for(:name).each do |message| %>
        <div class='error-message'><%= message %></div>
      <% end %>
    </div>
    <div>
      <%= f.label :icon %><br>
      <%= f.text_field :icon, autocomplete: 'icon', autofocus: true %>
      <% @category.errors.full_messages_for(:icon).each do |message| %>
        <div class='error-message'><%= message %></div>
      <% end %>
    </div>
    
    <div>
      <%= f.submit %>
    </div>
  <% end %>
    <div >
    <%= link_to "Back to categories", categories_path, class: "back-page" %>     
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>    
      <% if user_signed_in? %>            
        <%= render "shared/nav" %> 
       <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="nav main-bg">
  <i class="fa-solid fa-bars"></i>
  <h1><%= @page_name %></h1>
  <%= link_to 'Log out', destroy_user_session_path %> 
</nav>

app/views/splashes/index.html.erb
<div class="splash main-bg">
  <h1>Budget App</h1>
  <div class='links' >
    <%= link_to 'Sign in', new_user_registration_path %>      
    <%= link_to 'Log in', new_user_session_path %>      
  </div>
</div>

app/views/transactions/index.html.erb
<% @page_name ='Transactions' %>

<div class='transactions'>
  <% if @transactions.empty? %>
      <p>no transaction</p>         
  <% end %>

  <div class="total"> 
    <h3>Total: $<%= Transaction.where(category_id: @id).reduce(0) { |sum, t| sum + t.amount }  %></h3>
  </div>
  <% @transactions.each do |transaction| %>
    
    <div class='card'>
      <p class='name'><%= transaction.name%></p>
      <p>$<%= transaction.amount %></p>
    </div>
  <% end %>

  <div >
    <%= link_to "Back to categories", categories_path, class: "back-page" %>     
  </div>
</div>
<%= link_to "New transaction", new_category_transaction_path, class: 'btn' %>

app/views/transactions/new.html.erb
<% @page_name = "New Transaction" %>
<% @back = category_transactions_path(@id)%>

<div class='transaction-form'>
  <%= form_with url: category_transactions_path, scope: :transaction  do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label :amount %><br />
      <%= f.number_field :amount %>
    </div>

    <div class="field">
      <%= f.label :category %><br />
      <%= f.collection_select :category_id, Category.where(user_id: current_user.id).order(:name),:id,:name %>
    </div>

    <%= f.submit "Create Transaction" %>
  <% end %>

    <div >
    <%= link_to "Back to transaction", category_transactions_path, class: "back-page" %>     
  </div>
</div>